"""empty message

Revision ID: 63f521541e83
Revises: 8a4577c5d99f
Create Date: 2020-04-04 19:12:12.381303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f521541e83'
down_revision = '8a4577c5d99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###
